export const docsNavigation = [
  {
    label: 'Overview',
    items: [
      { href: '/docs/', label: 'What is Exstream' },
      { href: '/docs/project/when-not-to-use/', label: 'When to use it' },
      { href: '/docs/project/origin/', label: 'History' },
    ],
  },
  {
    label: 'Learn',
    items: [
      { href: '/docs/learn/pipeline-model/', label: 'Pipeline model' },
      { href: '/docs/learn/sources/', label: 'Create a source' },
      { href: '/docs/learn/transform-data/', label: 'Transform data' },
      { href: '/docs/learn/async-work/', label: 'Async processing' },
      { href: '/docs/learn/consume/', label: 'Consume a pipeline' },
      { href: '/docs/concepts/backpressure/', label: 'Backpressure' },
      { href: '/docs/learn/branching/', label: 'Branch & observe' },
      { href: '/docs/learn/errors/', label: 'Errors & lifecycle' },
    ],
  },
  {
    label: 'Guides',
    items: [{ href: '/docs/examples/browser-csv/', label: 'Fetch a large CSV' }],
  },
  {
    label: 'API reference',
    items: [{ href: '/docs/reference/', label: 'Operator index' }],
  },
  {
    label: 'API · Create',
    items: [
      { href: '/docs/reference/exstream/', label: 'exstream()' },
      { href: '/docs/reference/from-event/', label: 'fromEvent()' },
      { href: '/docs/reference/pipeline/', label: 'pipeline()' },
      { href: '/docs/reference/destination/', label: 'destination()' },
      { href: '/docs/reference/data/', label: 'data() & nil' },
    ],
  },
  {
    label: 'API · Context',
    items: [
      { href: '/docs/reference/with-context/', label: 'withContext()' },
      { href: '/docs/reference/extend-context/', label: 'extendContext()' },
      { href: '/docs/reference/stream-state/', label: 'Stream state' },
      { href: '/docs/reference/events/', label: 'Events' },
    ],
  },
  {
    label: 'API · Transform',
    items: [
      { href: '/docs/reference/map/', label: 'map()' },
      { href: '/docs/reference/flat-map/', label: 'flatMap()' },
      { href: '/docs/reference/flatten/', label: 'flatten()' },
      { href: '/docs/reference/tap/', label: 'tap()' },
      { href: '/docs/reference/compact/', label: 'compact()' },
      { href: '/docs/reference/pluck/', label: 'pluck()' },
      { href: '/docs/reference/pick/', label: 'pick()' },
      { href: '/docs/reference/omit/', label: 'omit()' },
      { href: '/docs/reference/batch/', label: 'batch()' },
    ],
  },
  {
    label: 'API · Select',
    items: [
      { href: '/docs/reference/filter/', label: 'filter()' },
      { href: '/docs/reference/reject/', label: 'reject()' },
      { href: '/docs/reference/find/', label: 'find()' },
      { href: '/docs/reference/where/', label: 'where()' },
      { href: '/docs/reference/find-where/', label: 'findWhere()' },
      { href: '/docs/reference/uniq/', label: 'uniq()' },
      { href: '/docs/reference/uniq-by/', label: 'uniqBy()' },
      { href: '/docs/reference/slice/', label: 'slice()' },
      { href: '/docs/reference/take/', label: 'take()' },
      { href: '/docs/reference/drop/', label: 'drop()' },
      { href: '/docs/reference/head/', label: 'head()' },
      { href: '/docs/reference/last/', label: 'last()' },
      { href: '/docs/reference/stop-when/', label: 'stopWhen()' },
    ],
  },
  {
    label: 'API · Aggregate',
    items: [
      { href: '/docs/reference/collect/', label: 'collect()' },
      { href: '/docs/reference/reduce/', label: 'reduce()' },
      { href: '/docs/reference/reduce-1/', label: 'reduce1()' },
      { href: '/docs/reference/group-by/', label: 'groupBy()' },
      { href: '/docs/reference/key-by/', label: 'keyBy()' },
      { href: '/docs/reference/sort/', label: 'sort()' },
      { href: '/docs/reference/sort-by/', label: 'sortBy()' },
      { href: '/docs/reference/sorted-group-by/', label: 'sortedGroupBy()' },
    ],
  },
  {
    label: 'API · Async',
    items: [
      { href: '/docs/reference/map-async/', label: 'mapAsync()' },
      { href: '/docs/reference/async-filter/', label: 'asyncFilter()' },
      { href: '/docs/reference/async-reduce/', label: 'asyncReduce()' },
      { href: '/docs/reference/make-async/', label: 'makeAsync()' },
    ],
  },
  {
    label: 'API · Graph',
    items: [
      { href: '/docs/reference/fork/', label: 'fork()' },
      { href: '/docs/reference/observe/', label: 'observe()' },
      { href: '/docs/reference/merge/', label: 'merge()' },
      { href: '/docs/reference/through/', label: 'through()' },
      { href: '/docs/reference/sorted-join/', label: 'sortedJoin()' },
    ],
  },
  {
    label: 'API · Errors',
    items: [
      { href: '/docs/reference/error-api/', label: 'Error API' },
      { href: '/docs/reference/errors/', label: 'errors()' },
      { href: '/docs/reference/skip-errors/', label: 'skipErrors()' },
      { href: '/docs/reference/fail-on-error/', label: 'failOnError()' },
      { href: '/docs/reference/route-errors/', label: 'routeErrors()' },
      { href: '/docs/reference/stop-on-error/', label: 'stopOnError()' },
    ],
  },
  {
    label: 'API · Formats',
    items: [
      { href: '/docs/reference/csv/', label: 'csv()' },
      { href: '/docs/reference/csv-stringify/', label: 'csvStringify()' },
      { href: '/docs/reference/json/', label: 'json()' },
      { href: '/docs/reference/json-stringify/', label: 'jsonStringify()' },
      { href: '/docs/reference/jsonl/', label: 'jsonl()' },
      { href: '/docs/reference/jsonl-stringify/', label: 'jsonlStringify()' },
      { href: '/docs/reference/split/', label: 'split()' },
      { href: '/docs/reference/split-by/', label: 'splitBy()' },
      { href: '/docs/reference/encode/', label: 'encode()' },
      { href: '/docs/reference/decode/', label: 'decode()' },
    ],
  },
  {
    label: 'API · Flow',
    items: [
      { href: '/docs/reference/throttle/', label: 'throttle()' },
      { href: '/docs/reference/ratelimit/', label: 'ratelimit()' },
    ],
  },
  {
    label: 'API · Consume',
    items: [
      { href: '/docs/reference/pipe-to/', label: 'pipeTo()' },
      { href: '/docs/reference/async-iteration/', label: 'Async iteration' },
      { href: '/docs/reference/to-web-readable/', label: 'toWebReadable()' },
      { href: '/docs/reference/to-node-readable/', label: 'toNodeReadable()' },
      { href: '/docs/reference/to-node-transform/', label: 'toNodeTransform()' },
      { href: '/docs/reference/to-array/', label: 'toArray()' },
      { href: '/docs/reference/drain/', label: 'drain()' },
      { href: '/docs/reference/single/', label: 'single()' },
    ],
  },
  {
    label: 'API · Low level',
    items: [
      { href: '/docs/reference/write/', label: 'write()' },
      { href: '/docs/reference/consume/', label: 'consume()' },
      { href: '/docs/reference/consume-sync/', label: 'consumeSync()' },
      { href: '/docs/reference/start/', label: 'start()' },
      { href: '/docs/reference/end/', label: 'end()' },
      { href: '/docs/reference/extend/', label: 'extend()' },
    ],
  },
] as const
